language: python

python:
  - "2.7"

install: "pip install -r requirements.txt"

cache: pip

before_script:
  - psql -c "create role alp with login password 'Trip-Tough-Basis-Brother-2';" -U postgres
  - psql -c "create database alp with owner alp;" -U postgres

script:
  - "cd tests"
  - "python -m unittest discover -p '*_test.py'"
  - "python urls_functionality.py"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d0ad60bd0683917e29b
    on_success: always
    on_failure: always
    on_start: change

addons:
  postgresql: "9.4"

services:
  - postgresql
